name: Publish

#
#
# ~ IMPORTANT ~
# If your commit summary starts with `Release`
#   - We will attempt to automatically publish your commit (although, your commit will not be automatically approved)
#   - *NOTE*
#   - We will attempt to create a new release using the commit description as release notes
#
#

on:
  push:
    branches:
      - main
      - master

jobs:
  publish:
    if: startsWith(github.event.head_commit.message, 'Release ')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          always-auth: true
          registry-url: 'https://npm.pkg.github.com'
          node-version: '14.17.3'
      - name: Publish
        run: |
          npm install
          npm run build
          npm run test
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  create-release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: |
          RV=$(echo $${{ github.event.head_commit.message }} | awk '{print $NF}')
          echo "RELEASE_VERSION=$RV" >> $GITHUB_ENV
          echo $RV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
